version: 6.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
environment:
  matrix:
  - solution_name: Src/SourceGrid.sln
  - solution_name: Src/WindowsFormsSample/WindowsFormsSample.sln
before_build:
- cmd: dotnet restore %solution_name%
build:
  project: '%solution_name%'
  verbosity: minimal
test:
  assemblies:
    only:
    - Out\Test\Release\SourceGrid.Tests.dll
artifacts:
- path: Out\
  name: SourceGrid
