version: 6.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
configuration: Release
environment:
  matrix:
  - solution_name: SourceGrid_All.sln
  - solution_name: Src/WindowsFormsSample/WindowsFormsSample.sln
install:
- cmd: nuget update -self
before_build:
- cmd: nuget restore
build:
  project: '%solution_name%'
  verbosity: minimal
test:
  assemblies:
    only:
    - Out\Test\Release\SourceGrid.Tests.dll
artifacts:
- path: Out\
  name: SourceGrid
